#!/bin/sh

echo "Seed DB & configure Sphinx"

/etc/init.d/mysql start

#only do 1st time
mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'root'@'%';"
mysql -uroot < db/seed.sql

#add content to some tables
zcat db/seed_data/diveboard/countries.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/countries_regions.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/areas.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/area_categories.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/i18n_languages.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/locations.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/locations_regions.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/regions.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/schema_migrations.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/geonames_cores.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/geonames_countries.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/geonames_featurecodes.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/spots.sql.gz | mysql -uroot -D diveboard
zcat db/seed_data/diveboard/wikis.sql.gz | mysql -uroot -D diveboard

#only do 1st time
bundle exec rake ts:configure 
bundle exec rake ts:index
bundle exec rake assets:jammit
bundle exec rake assets:precompile

/etc/init.d/mysql stop

#move files to persistant storage
mkdir -p /home/diveboard/diveboard-web/current/tmp/mysql
cp -rf /var/lib/mysql/* /home/diveboard/diveboard-web/current/tmp/mysql/
echo "Stopping all FS is ready - next time launch start_all instead!"