- Courses:
    CMAS:
      - One Star Diver
      - Two Stars Diver
      - Three Stars Diver
      - Four Stars Diver
      - Enriched Air Nitrox
      - Advanced Nitrox
      - Dry Suit
      - Photography
    PADI:
      - Open Water
      - Advanced Open Water
      - Rescue Diver
      - Master Diver
      - Divemaster
      - Open Water Scuba Instructor
      - Enriched Air Nitrox
      - Dry Suit
      - Photography
    SSI:
      - Open Water
      - Advanced Open Water
      - Rescue Diver
      - Master Diver
      - Divemaster
      - Open Water Instructor
      - Enriched Air Nitrox
      - Dry Suit
      - Photography
    BSAC:
      - Ocean Diver
      - Sports Diver
      - Dive Leader
      - Advanced Diver
      - Enriched Air Nitrox
    NAUI:
      - Scuba diver
      - Advanced Scuba Diver
      - Scuba Rescue Diver
      - Master Scuba Diver
      - Enriched Air Nitrox
    UTD:
      - Open Water
      - Essentials of Recreational Diving (REC1)
      - Essentials of Technical Diving
      - Nitrox (REC 2)
      - Helitrox (REC 3)
    SNSI:
      - Open Water
      - Advanced Open Water
      - Rescue Diver
      - Master Diver
      - Divemaster
      - Open Water Scuba Instructor
      - Enriched Air Nitrox
      - Dry Suit
      - Photography


- Dives:
  - Introductory Scuba Dive
  - Snorkel
  - Single dive
  - Guided dive
  - Single Dive with Nitrox
  - Two tank dive
  - Night dive
  - 5 dives package
  - 10 dives package
  - Shore Dive
  - Special trips (please detail...)

- Rental:
  - Full gear
  - Per element (Regulator, computer, BCD, wet suit, mask & fins)
  - Dive Light
  - Camera
  - Scooter / DPV

- Liveaboard:
  - Route 1 (please detail route...)
  - Route 2 (please detail route...)
  - Route 3 (please detail route...)


- Accomodation:
  - Single Occupancy
  - Double Occupancy
  - Four People
  - With Breakfast
  - All Meals
  - All Inclusive




