#!/bin/bash

# Cronic v2 - cron job report wrapper
# Copyright 2007 Chuck Houpt. No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/

#For Diveboard: Cronic is located in the script directory, and we want to log in ../log/cronic.log
SELF=`which "$0"`
DIR=`dirname "$SELF"`
OUTPUT="$DIR/../log/cronic.log"
STARTING_DATE=`date '+%Y-%m-%d %H:%M'`
MAIN_COMMAND=`basename $1 |sed 's/[^a-zA-Z0-9_.-]/./g'`

set -eu

OUT=/tmp/cronic.out.$$
ERR=/tmp/cronic.err.$$
TRACE=/tmp/cronic.trace.$$

set +e
"$@" >$OUT 2>$TRACE
RESULT=$?
set -e
ENDING_DATE=`date '+%Y-%m-%d %H:%M'`

PATTERN="^${PS4:0:1}\\+${PS4:1}"
if grep -aq "$PATTERN" $TRACE
then
    ! grep -av "$PATTERN" $TRACE > $ERR
else
    ERR=$TRACE
fi

#For Diveboard: always log in logfile
echo COMMAND: $@ | sed "s/^/$STARTING_DATE - $MAIN_COMMAND - $$ - /">> $OUTPUT
echo RESULT CODE: $RESULT | sed "s/^/$ENDING_DATE - $MAIN_COMMAND - $$ - /">> $OUTPUT
echo ERROR OUTPUT: | sed "s/^/$ENDING_DATE - $MAIN_COMMAND - $$ - /">> $OUTPUT
cat "$ERR" | sed "s/^/$ENDING_DATE - $MAIN_COMMAND - $$ - /">> $OUTPUT
echo "STANDARD OUTPUT:" | sed "s/^/$ENDING_DATE - $MAIN_COMMAND - $$ - /">> $OUTPUT
cat "$OUT" | sed "s/^/$ENDING_DATE - $MAIN_COMMAND - $$ - /">> $OUTPUT
if [ $TRACE != $ERR ]
then
    echo "TRACE-ERROR OUTPUT:" | sed "s/^/$ENDING_DATE - $MAIN_COMMAND - $$ - /">> $OUTPUT
    cat "$TRACE" | sed "s/^/$ENDING_DATE - $MAIN_COMMAND - $$ - /" >> $OUTPUT
fi


if [ $RESULT -ne 0 ]
    then
    echo "Cronic detected failure or error output for the command:"
    echo "$@"
    echo
    echo "RESULT CODE: $RESULT"
    echo
    echo "ERROR OUTPUT:"
    cat "$ERR"
    echo
    echo "STANDARD OUTPUT:"
    cat "$OUT"
    if [ $TRACE != $ERR ]
    then
        echo
        echo "TRACE-ERROR OUTPUT:"
        cat "$TRACE"
    fi
fi

rm -f "$OUT"
rm -f "$ERR"
rm -f "$TRACE"
